name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate config file
        run: |
          echo 'const config = {
            firebase: {
              apiKey: "'${{ secrets.FIREBASE_API_KEY }}'",
              authDomain: "'${{ secrets.FIREBASE_AUTH_DOMAIN }}'",
              databaseURL: "'${{ secrets.FIREBASE_DATABASE_URL }}'",
              projectId: "'${{ secrets.FIREBASE_PROJECT_ID }}'",
              storageBucket: "'${{ secrets.FIREBASE_STORAGE_BUCKET }}'",
              messagingSenderId: "'${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}'",
              appId: "'${{ secrets.FIREBASE_APP_ID }}'",
              measurementId: "'${{ secrets.FIREBASE_MEASUREMENT_ID }}'"
            },
            cloudinary: {
              cloudName: "'${{ secrets.CLOUDINARY_CLOUD_NAME }}'",
              apiKey: "'${{ secrets.CLOUDINARY_API_KEY }}'",
              apiSecret: "'${{ secrets.CLOUDINARY_API_SECRET }}'"
            }
          };' > config.js

      - name: Debug secrets
        run: |
          echo "Checking if secrets are set:"
          echo "FIREBASE_API_KEY length: ${#FIREBASE_API_KEY}"
          echo "FIREBASE_AUTH_DOMAIN length: ${#FIREBASE_AUTH_DOMAIN}"
          echo "CLOUDINARY_CLOUD_NAME length: ${#CLOUDINARY_CLOUD_NAME}"
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}

      - name: Verify config file
        run: |
          echo "Config file contents:"
          cat config.js
          echo "File exists check:"
          ls -l config.js

      - name: Create .nojekyll
        run: touch .nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          force_orphan: true 
