name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Inject config into HTML
        run: |
          echo "Injecting config into HTML..."
          CONFIG="const config = {
            firebase: {
              apiKey: '${FIREBASE_API_KEY}',
              authDomain: '${FIREBASE_AUTH_DOMAIN}',
              databaseURL: '${FIREBASE_DATABASE_URL}',
              projectId: '${FIREBASE_PROJECT_ID}',
              storageBucket: '${FIREBASE_STORAGE_BUCKET}',
              messagingSenderId: '${FIREBASE_MESSAGING_SENDER_ID}',
              appId: '${FIREBASE_APP_ID}',
              measurementId: '${FIREBASE_MEASUREMENT_ID}'
            },
            cloudinary: {
              cloudName: '${CLOUDINARY_CLOUD_NAME}',
              apiKey: '${CLOUDINARY_API_KEY}',
              apiSecret: '${CLOUDINARY_API_SECRET}'
            }
          };"
          sed -i 's@<script src="config.js"></script>@<script>'"$CONFIG"'</script>@' index.html
        env:
          FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
          CLOUDINARY_CLOUD_NAME: ${{ secrets.CLOUDINARY_CLOUD_NAME }}
          CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
          CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}

      - name: Create .nojekyll
        run: touch .nojekyll

      - name: Create deployment directory
        run: |
          mkdir deploy
          cp index.html deploy/
          cp .nojekyll deploy/
          cp -r .github deploy/
          cp .gitignore deploy/
          cp .env.example deploy/
          cp config.example.js deploy/
          echo "Deployment directory contents:"
          ls -la deploy/
          echo "Verifying HTML content:"
          grep -A 10 "const config" deploy/index.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy
          force_orphan: true
          enable_jekyll: false

      - name: Verify deployment
        run: |
          sleep 30
          echo "Checking deployment..."
          curl -I https://loimio.github.io/Mio/ || true 
