name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate config file
        run: |
          cat > config.js << 'EOL'
          const config = {
            firebase: {
              apiKey: "${{ secrets.FIREBASE_API_KEY }}",
              authDomain: "${{ secrets.FIREBASE_AUTH_DOMAIN }}",
              databaseURL: "${{ secrets.FIREBASE_DATABASE_URL }}",
              projectId: "${{ secrets.FIREBASE_PROJECT_ID }}",
              storageBucket: "${{ secrets.FIREBASE_STORAGE_BUCKET }}",
              messagingSenderId: "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}",
              appId: "${{ secrets.FIREBASE_APP_ID }}",
              measurementId: "${{ secrets.FIREBASE_MEASUREMENT_ID }}"
            },
            cloudinary: {
              cloudName: "${{ secrets.CLOUDINARY_CLOUD_NAME }}",
              apiKey: "${{ secrets.CLOUDINARY_API_KEY }}",
              apiSecret: "${{ secrets.CLOUDINARY_API_SECRET }}"
            }
          };
          EOL

      - name: List files before deploy
        run: |
          echo "Current directory contents before deploy:"
          pwd
          ls -la
          echo "Config.js location and contents:"
          find . -name config.js
          cat config.js

      - name: Create .nojekyll
        run: touch .nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          force_orphan: true

      - name: Wait for deployment
        run: sleep 30

      - name: Check deployment
        run: |
          echo "Checking if config.js is accessible..."
          curl -I https://loimio.github.io/Mio/config.js 
