name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List current directory
        run: |
          echo "Current directory contents before:"
          ls -la

      - name: Generate config file
        id: generate-config
        run: |
          echo "Creating config.js file..."
          echo "const config = {
            firebase: {
              apiKey: '${{ secrets.FIREBASE_API_KEY }}',
              authDomain: '${{ secrets.FIREBASE_AUTH_DOMAIN }}',
              databaseURL: '${{ secrets.FIREBASE_DATABASE_URL }}',
              projectId: '${{ secrets.FIREBASE_PROJECT_ID }}',
              storageBucket: '${{ secrets.FIREBASE_STORAGE_BUCKET }}',
              messagingSenderId: '${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}',
              appId: '${{ secrets.FIREBASE_APP_ID }}',
              measurementId: '${{ secrets.FIREBASE_MEASUREMENT_ID }}'
            },
            cloudinary: {
              cloudName: '${{ secrets.CLOUDINARY_CLOUD_NAME }}',
              apiKey: '${{ secrets.CLOUDINARY_API_KEY }}',
              apiSecret: '${{ secrets.CLOUDINARY_API_SECRET }}'
            }
          };" > config.js
          echo "Config file created successfully"
          echo "Config file contents:"
          cat config.js

      - name: Verify config file
        run: |
          echo "Checking if config.js exists:"
          ls -la config.js
          echo "Current directory contents after:"
          ls -la

      - name: Create .nojekyll
        run: touch .nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          force_orphan: true 
